### ISSUE TITLE
[BUG] Game crashes whenever you load a map.

### ISSUE THREAD

**Issue by Jordon87** [KiwifruitDev/DirectorsCut#15]
Since this tool has recently changed to the MP 2013 branch lately, I've noticed a few problems while testing this out.

For instance, if you try to load any of your maps (e.g. my personal ported Serious Room map) The game will crash instantly. Last time this was on the Mapbase branch there were no problems at all.

However, if you load sdk_vehicles, and _then_ load one of your maps, the game will still work without any crashing. I'm aware this problem will get fixed but I'm only giving out the message.

**Comment by KiwifruitDev** [comment]
Hi, a new build using the 2013 MP branch is available. Mind giving it a shot?

**Comment by Jordon87** [comment]
It works now. Thanks.
