### ISSUE TITLE
CAN'T LAUNCH IT!

### ISSUE THREAD

**Issue by Loganthegamer12678** [KiwifruitDev/DirectorsCut#16]
I EXTRACTED IT TO SOURCEMODS LIKE YOU TOLD ME TO DO! I EVEN INSTALLED SOURCE 2013 MULTIPLAYER!!! WHY CAN'T I LAUNCH IIIIT!!!!!!!!!!!!!!!!

**Comment by Loganthegamer12678** [comment]
WHY DO I HAVE TO INSTALL SINGLEPLAYER?! YOU F'ING LIARS!!

**Comment by KiwifruitDev** [comment]
There hasn't been a build for SDK MP because we had just switched over and the automated build system is in progress.

This issue will be closed.

You have been blocked from KiwifruitDev/DirectorsCut.
